language: python

sudo: false

matrix:
  include:
    # Only one test for these Python versions
    - env: ENV_FILE="requirements/requirements_linux.txt"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda config --add channels anaconda
  - conda config --add channels conda-forge

  # Install dependencies
  # - conda env create --file="${ENV_FILE}"
  - conda create --name test --file "${ENV_FILE}"
  - source activate test
  - pip install -e .
  - conda list

script:
  - python setup.py lint
  - python setup.py mypy
  - pytest tests --cov geonurse -v --cov-report term-missing

after_success:
  - codecov
