language: python

sudo: false

matrix:
  include:
    # Only one test for these Python versions
    - env: ENV_FILE="ci/travis/linux_env"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create --name test --file "${ENV_FILE}"
  - source activate test
  - pip install -e .
  - conda list

script:
  - python setup.py lint
  - python setup.py mypy
  - python setup.py test
