name: geonurse
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - coverage
  - dask
  - geopandas=>0.5.0
  - ipykernel
  - jupyter
  - pyarrow
  - pylint
  - pyspark=2.4.0
  - pytest
  - pytest-cov
  - pytest-runner
  - python=3.7
  - rtree
  - tqdm
